create extension if not exists btree_gist;
create table providers (id text primary key,name text not null,type text not null check(type in ('PANDIT','ASTROLOGER')),active boolean not null default true,timezone text not null default 'Asia/Kolkata',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table provider_services (provider_id text not null references providers(id),service_slug text not null,duration_minutes integer not null check(duration_minutes>0),buffer_before_minutes integer not null default 0 check(buffer_before_minutes>=0),buffer_after_minutes integer not null default 0 check(buffer_after_minutes>=0),capacity integer not null default 1 check(capacity>0),booking_mode text not null check(booking_mode in ('INSTANT','REQUEST')),allowed_location_modes text[] not null,active boolean not null default true,primary key(provider_id,service_slug));
create table availability_rules (id text primary key,provider_id text not null references providers(id),day_of_week integer not null check(day_of_week between 0 and 6),local_start_time time not null,local_end_time time not null,timezone text not null,capacity integer not null default 1 check(capacity>0),active boolean not null default true,check(local_start_time<local_end_time));
create table availability_exceptions (id text primary key,provider_id text not null references providers(id),local_date date not null,type text not null check(type in ('UNAVAILABLE','CUSTOM_HOURS')),local_start_time time,local_end_time time,capacity integer check(capacity>0),unique(provider_id,local_date),check(type='UNAVAILABLE' or (local_start_time is not null and local_end_time is not null and local_start_time<local_end_time)));
create table bookings (id bigint generated always as identity primary key,reference text not null unique,provider_id text not null,service_slug text not null,customer_name text not null,customer_email text not null,customer_phone text,location_mode text not null check(location_mode in ('ONLINE','CUSTOMER_LOCATION','TEMPLE','OFFICE')),venue text,timezone text not null,local_date date not null,local_time time not null,requested_start timestamptz not null,requested_end timestamptz not null,occupied_start timestamptz not null,occupied_end timestamptz not null,status text not null check(status in ('REQUESTED','PENDING_CONFIRMATION','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED')),customer_message text,capacity_used integer not null default 1 check(capacity_used>0),buffer_before_minutes integer not null,buffer_after_minutes integer not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(provider_id,service_slug) references provider_services(provider_id,service_slug),check(requested_start<requested_end),check(occupied_start<=requested_start and occupied_end>=requested_end));
create index bookings_provider_occupied_idx on bookings using gist(provider_id,tstzrange(occupied_start,occupied_end,'[)')) where status in ('REQUESTED','PENDING_CONFIRMATION','CONFIRMED','IN_PROGRESS');
create index availability_rules_provider_idx on availability_rules(provider_id,day_of_week) where active;
create index availability_exceptions_provider_date_idx on availability_exceptions(provider_id,local_date);
