'use client';

import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';

type Booking={id:string;reference:string;providerId:string;providerName:string;serviceSlug:string;customerName:string;customerEmail:string;customerPhone?:string;locationMode:string;venue?:string;localDate:string;localTime:string;status:string;customerMessage?:string;adminNotes?:string;meetingUrl?:string;events?:Array<{type:string;actor:string;details:unknown;createdAt:string}>};
type Provider={id:string;name:string};
type Mutate=(payload:Record<string,unknown>)=>Promise<void>;
const statuses=['REQUESTED','PENDING_CONFIRMATION','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED'];

export function BookingsManager({bookings,providers,mutate,selectedBookingId,onSelectedBookingHandled}:{bookings:Booking[];providers:Provider[];mutate:Mutate;selectedBookingId?:string;onSelectedBookingHandled?:()=>void}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[provider,setProvider]=useState('');
 useEffect(()=>{if(selectedBookingId){setQuery('');setStatus('');setProvider('')}},[selectedBookingId]);
 const filtered=useMemo(()=>bookings.filter(b=>(!status||b.status===status)&&(!provider||b.providerId===provider)&&(!query||`${b.reference} ${b.customerName} ${b.customerEmail} ${b.customerPhone||''} ${b.serviceSlug}`.toLowerCase().includes(query.toLowerCase()))),[bookings,query,status,provider]);
 return <section className="admin-panel"><div className="panel-title"><h2>Bookings</h2><p>Search, review, update, and reschedule customer orders.</p></div><div className="booking-filters"><input aria-label="Search bookings" placeholder="Search reference, customer, phone, email…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s.replaceAll('_',' ')}</option>)}</select><select aria-label="Filter by provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="">All practitioners</option>{providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><b>{filtered.length} results</b></div><div className="booking-list">{filtered.map(b=><BookingCard booking={b} mutate={mutate} key={b.id} initiallyOpen={b.id===selectedBookingId} onOpened={b.id===selectedBookingId?onSelectedBookingHandled:undefined}/>)}</div>{!filtered.length&&<p className="admin-empty">No bookings match these filters.</p>}</section>
}

function BookingCard({booking:b,mutate,initiallyOpen,onOpened}:{booking:Booking;mutate:Mutate;initiallyOpen?:boolean;onOpened?:()=>void}){
 const detailsRef=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{if(initiallyOpen&&detailsRef.current){detailsRef.current.open=true;detailsRef.current.scrollIntoView({behavior:'smooth',block:'center'});detailsRef.current.focus();onOpened?.()}},[initiallyOpen,onOpened]);
 function status(event:FormEvent<HTMLFormElement>){event.preventDefault();const v=new FormData(event.currentTarget);void mutate({action:'booking-status',id:b.id,status:v.get('status'),adminNotes:v.get('adminNotes'),meetingUrl:v.get('meetingUrl')})}
 function reschedule(event:FormEvent<HTMLFormElement>){event.preventDefault();const v=new FormData(event.currentTarget);void mutate({action:'booking-reschedule',id:b.id,localDate:v.get('localDate'),localTime:v.get('localTime'),status:v.get('status')})}
 return <details className="booking-card" ref={detailsRef} tabIndex={-1} data-booking-id={b.id}><summary><span><b>{b.reference}</b><small>{b.serviceSlug.replaceAll('-',' ')} · {b.customerName}</small></span><span>{b.localDate}<small>{b.localTime} · {b.providerName}</small></span><i className={`status-pill s-${b.status.toLowerCase()}`}>{b.status.replaceAll('_',' ')}</i></summary><div className="booking-detail"><section><h3>Customer and location</h3><p>{b.customerEmail||'No email provided'}<br/>{b.customerPhone||'No phone'}<br/>{b.locationMode.replaceAll('_',' ')}{b.venue?<><br/>{b.venue}</>:null}</p>{b.customerMessage&&<blockquote>{b.customerMessage}</blockquote>}</section><form onSubmit={status}><h3>Status and notes</h3><label>Status<select name="status" defaultValue={b.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Meeting link<input type="url" name="meetingUrl" defaultValue={b.meetingUrl||''} placeholder="https://…"/></label><label>Private admin notes<textarea name="adminNotes" defaultValue={b.adminNotes||''} rows={3}/></label><button>Save details</button></form><form onSubmit={reschedule}><h3>Reschedule</h3><label>New date<input type="date" name="localDate" defaultValue={b.localDate} required/></label><label>New time<input type="time" name="localTime" defaultValue={b.localTime} required/></label><label>Resulting status<select name="status" defaultValue="CONFIRMED"><option>CONFIRMED</option><option>PENDING_CONFIRMATION</option><option>REQUESTED</option></select></label><button>Check conflict & reschedule</button></form>{b.events&&b.events.length>0&&<section className="booking-history"><h3>History</h3>{b.events.slice(0,8).map((e,i)=><p key={`${e.createdAt}-${i}`}><b>{e.type.replaceAll('_',' ')}</b><small>{e.actor} · {new Date(e.createdAt).toLocaleString()}</small></p>)}</section>}</div></details>
}

export function AdminCalendar({bookings,onOpenBooking}:{bookings:Booking[];onOpenBooking:(id:string)=>void}){
 const [anchor,setAnchor]=useState(()=>new Date()),start=useMemo(()=>{const d=new Date(anchor);d.setDate(d.getDate()-((d.getDay()+6)%7));d.setHours(0,0,0,0);return d},[anchor]),days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d}),active=bookings.filter(b=>!['CANCELLED','REJECTED'].includes(b.status));
 return <section className="admin-panel"><div className="calendar-head"><div><h2>Weekly calendar</h2><p>{days[0].toLocaleDateString()} – {days[6].toLocaleDateString()}</p></div><div><button onClick={()=>setAnchor(new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()-7))}>← Previous</button><button onClick={()=>setAnchor(new Date())}>Today</button><button onClick={()=>setAnchor(new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()+7))}>Next →</button></div></div><p className="calendar-hint">Select an order to open its booking details.</p><div className="week-grid">{days.map(day=>{const key=day.toLocaleDateString('en-CA'),items=active.filter(b=>b.localDate===key).sort((a,b)=>a.localTime.localeCompare(b.localTime));return <section key={key}><header><b>{day.toLocaleDateString(undefined,{weekday:'short'})}</b><span>{day.getDate()}</span></header>{items.map(b=><button type="button" className="calendar-order" key={b.id} onClick={()=>onOpenBooking(b.id)} aria-label={`Open booking ${b.reference} for ${b.customerName}`}><time>{b.localTime}</time><b>{b.customerName}</b><small>{b.reference}<br/>{b.providerName}<br/>{b.serviceSlug.replaceAll('-',' ')}</small><span>View order →</span></button>)}{!items.length&&<p>No bookings</p>}</section>})}</div></section>
}
