'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AdminCalendar,BookingsManager} from './booking-tools';

type Provider={id:string;name:string;type:'PANDIT'|'ASTROLOGER'|'NUMEROLOGIST';active:boolean;timezone:string;slug?:string;bio?:string;experienceYears?:number|null;city?:string;languages?:string[];specialties?:string[];qualifications?:string;photoUrl?:string;published?:boolean};
type Booking={id:string;reference:string;providerId:string;providerName:string;serviceSlug:string;customerName:string;customerEmail:string;customerPhone?:string;locationMode:string;venue?:string;localDate:string;localTime:string;requestedStart:string;requestedEnd:string;status:string;customerMessage?:string;adminNotes?:string;meetingUrl?:string;createdAt:string;events?:Array<{type:string;actor:string;details:unknown;createdAt:string}>};
type Service={providerId:string;serviceSlug:string;durationMinutes:number;bufferBeforeMinutes:number;bufferAfterMinutes:number;capacity:number;bookingMode:'INSTANT'|'REQUEST';allowedLocationModes:string[];active:boolean};
type Rule={id:string;providerId:string;dayOfWeek:number;localStartTime:string;localEndTime:string;timezone:string;capacity:number;active:boolean};
type Exception={id:string;providerId:string;localDate:string;type:'UNAVAILABLE'|'CUSTOM_HOURS';localStartTime?:string;localEndTime?:string;capacity?:number};
type Enquiry={id:string;reference:string;name:string;email:string;serviceSlug?:string;pujaCategory?:string;preferredDate?:string;message?:string;status:string;createdAt:string};
type Dashboard={bookings:Booking[];providers:Provider[];services:Service[];rules:Rule[];exceptions:Exception[];enquiries:Enquiry[]};
type Submit=(e:FormEvent<HTMLFormElement>,a:string,t?:(v:Record<string,FormDataEntryValue>)=>Record<string,unknown>)=>void;
const EMPTY:Dashboard={bookings:[],providers:[],services:[],rules:[],exceptions:[],enquiries:[]};
const statuses=['REQUESTED','PENDING_CONFIRMATION','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED'];
const serviceNames:Record<string,string>={'astrology':'Astrology','online-puja':'Online Puja','puja-rituals':'Puja & Rituals','bratopanayan':'Bratopanayan','marriage':'Marriage'};
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const locationModes=['ONLINE','CUSTOMER_LOCATION','TEMPLE','OFFICE'];
const values=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));

export default function AdminDashboard(){
 const router=useRouter(),[data,setData]=useState(EMPTY),[tab,setTab]=useState('bookings'),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{setBusy(true);try{const response=await fetch('/api/admin',{cache:'no-store'});if(response.status===401){router.replace('/admin/login');return}const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load admin data.')}finally{setBusy(false)}},[router]);
 useEffect(()=>{void load()},[load]);
 async function mutate(payload:Record<string,unknown>){setMessage('Saving…');setError('');const response=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(response.status===401){router.replace('/admin/login');return}if(!response.ok){setMessage('');setError(body.message||'Change could not be saved.');return}setMessage('Saved.');await load()}
 async function submit(event:FormEvent<HTMLFormElement>,action:string,transform?:(v:Record<string,FormDataEntryValue>)=>Record<string,unknown>){event.preventDefault();const raw=values(event.currentTarget);await mutate({action,...(transform?transform(raw):raw)})}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});router.replace('/admin/login');router.refresh()}
 const counts=useMemo(()=>({new:data.bookings.filter(b=>['REQUESTED','PENDING_CONFIRMATION'].includes(b.status)).length,today:data.bookings.filter(b=>b.localDate===new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})).length,providers:data.providers.filter(p=>p.active).length}),[data]);
 return <main className="admin-shell"><header className="admin-top"><div><img src="/shuvamstu-logo.jpg" alt="Shuvamstu"/><span>Scheduling Admin</span></div><button className="admin-quiet" onClick={logout}>Sign out</button></header><div className="admin-body"><section className="admin-heading"><div><p className="admin-eyebrow">Operations</p><h1>Scheduling dashboard</h1></div><button onClick={load} disabled={busy}>↻ Refresh</button></section><section className="admin-stats"><article><b>{counts.new}</b><span>Awaiting action</span></article><article><b>{counts.today}</b><span>Bookings today</span></article><article><b>{counts.providers}</b><span>Active providers</span></article></section><nav className="admin-tabs">{[['bookings','Bookings'],['enquiries','Enquiries'],['calendar','Calendar'],['providers','Providers'],['services','Services'],['availability','Weekly hours'],['exceptions','Leave & exceptions']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{message&&<p className="admin-notice">{message}</p>}{error&&<p className="admin-error" role="alert">{error}</p>}{busy&&!data.providers.length?<p className="admin-loading">Loading scheduling data…</p>:<>{tab==='bookings'&&<BookingsManager bookings={data.bookings} providers={data.providers} mutate={mutate}/>} {tab==='enquiries'&&<Enquiries enquiries={data.enquiries} mutate={mutate}/>} {tab==='calendar'&&<AdminCalendar bookings={data.bookings}/>} {tab==='providers'&&<Providers providers={data.providers} submit={submit}/>} {tab==='services'&&<Services data={data} submit={submit}/>} {tab==='availability'&&<Availability data={data} submit={submit} mutate={mutate}/>} {tab==='exceptions'&&<Exceptions data={data} submit={submit} mutate={mutate}/>}</>}</div></main>
}

function Enquiries({enquiries,mutate}:{enquiries:Enquiry[];mutate:(p:Record<string,unknown>)=>Promise<void>}){return <section className="admin-panel"><PanelTitle title="Enquiries" text="Saved enquiries remain available even when webhook delivery fails."/>{!enquiries.length?<Empty text="No enquiries yet."/>:<div className="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Requirement</th><th>Message</th><th>Status</th></tr></thead><tbody>{enquiries.map(item=><tr key={item.id}><td><b>{item.reference}</b><small>{new Date(item.createdAt).toLocaleString()}</small></td><td>{item.name}<small>{item.email}</small></td><td>{item.serviceSlug||'General'}<small>{item.pujaCategory||item.preferredDate||''}</small></td><td>{item.message||'—'}</td><td><select value={item.status} onChange={event=>mutate({action:'enquiry-status',id:item.id,status:event.target.value})}>{['NEW','CONTACTED','CONVERTED','CLOSED'].map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>}</section>}

function Bookings({bookings,mutate}:{bookings:Booking[];mutate:(p:Record<string,unknown>)=>Promise<void>}){return <section className="admin-panel"><PanelTitle title="Bookings" text="Latest 250 requests and appointments."/>{!bookings.length?<Empty text="No bookings yet."/>:<div className="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Schedule</th><th>Provider</th><th>Status</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><b>{b.reference}</b><small>{serviceNames[b.serviceSlug]||b.serviceSlug}</small></td><td>{b.customerName}<small>{b.customerEmail}{b.customerPhone?` · ${b.customerPhone}`:''}</small></td><td>{b.localDate} · {b.localTime}<small>{b.locationMode.replaceAll('_',' ')}{b.venue?` · ${b.venue}`:''}</small></td><td>{b.providerName}</td><td><select value={b.status} onChange={e=>mutate({action:'booking-status',id:b.id,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>}</section>}

function Providers({providers,submit}:{providers:Provider[];submit:Submit}){return <section className="admin-panel"><PanelTitle title="Providers" text="Add pandits and astrologers, or deactivate them without deleting history."/><div className="admin-cards"><ProviderForm submit={submit}/>{providers.map(p=><ProviderForm key={p.id} provider={p} submit={submit}/>)}</div></section>}
function ProviderForm({provider,submit}:{provider?:Provider;submit:Submit}){return <form className="admin-card provider-profile-form" onSubmit={e=>submit(e,'provider-save',v=>({...v,experienceYears:v.experienceYears===''?'':Number(v.experienceYears),languages:String(v.languages||'').split(',').map(x=>x.trim()).filter(Boolean),specialties:String(v.specialties||'').split(',').map(x=>x.trim()).filter(Boolean),active:v.active==='on',published:v.published==='on'}))}><div className="profile-form-title"><h3>{provider?'Edit profile':'Add practitioner'}</h3>{provider?.published&&<span>Published</span>}</div>{provider&&<input type="hidden" name="id" value={provider.id}/>}<div className="form-grid"><label>Name<input name="name" defaultValue={provider?.name} required maxLength={100}/></label><label>Profile URL slug<input name="slug" defaultValue={provider?.slug||''} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="ramesh-sharma"/></label><label>Type<select name="type" defaultValue={provider?.type||'PANDIT'}><option>PANDIT</option><option>ASTROLOGER</option><option>NUMEROLOGIST</option></select></label><label>Experience (years)<input name="experienceYears" type="number" min="0" max="100" defaultValue={provider?.experienceYears??''}/></label><label>City<input name="city" defaultValue={provider?.city||''}/></label><label>Timezone<input name="timezone" defaultValue={provider?.timezone||'Asia/Kolkata'} required/></label></div><label>Languages <small>Comma-separated</small><input name="languages" defaultValue={provider?.languages?.join(', ')||''} placeholder="Odia, Hindi, English"/></label><label>Specialties <small>Comma-separated</small><input name="specialties" defaultValue={provider?.specialties?.join(', ')||''} placeholder="Marriage, Griha Pravesh"/></label><label>Qualifications<textarea name="qualifications" rows={2} defaultValue={provider?.qualifications||''}/></label><label>Biography<textarea name="bio" rows={5} maxLength={3000} defaultValue={provider?.bio||''} placeholder="A factual professional introduction…"/></label><label>Photo URL <small>HTTPS image URL</small><input name="photoUrl" type="url" defaultValue={provider?.photoUrl||''} placeholder="https://…"/></label><div className="profile-checks"><label className="check"><input name="active" type="checkbox" defaultChecked={provider?.active??true}/> Active for scheduling</label><label className="check"><input name="published" type="checkbox" defaultChecked={provider?.published??false}/> Publish profile publicly</label></div><button>Save practitioner</button></form>}

function Services({data,submit}:{data:Dashboard;submit:Submit}){return <section className="admin-panel"><PanelTitle title="Provider services" text="Assign services and control duration, buffers, booking mode, and capacity."/>{!data.providers.length?<Empty text="Add a provider first."/>:<div className="admin-cards"><ServiceForm providers={data.providers} submit={submit}/>{data.services.map(s=><ServiceForm key={`${s.providerId}-${s.serviceSlug}`} providers={data.providers} service={s} submit={submit}/>)}</div>}</section>}
function ServiceForm({providers,service,submit}:{providers:Provider[];service?:Service;submit:Submit}){return <form className="admin-card wide" onSubmit={e=>submit(e,'service-save',v=>({...v,durationMinutes:Number(v.durationMinutes),bufferBeforeMinutes:Number(v.bufferBeforeMinutes),bufferAfterMinutes:Number(v.bufferAfterMinutes),capacity:Number(v.capacity),active:v.active==='on',allowedLocationModes:locationModes.filter(m=>v[`location_${m}`]==='on')}))}><h3>{service?'Edit assignment':'Assign service'}</h3><label>Provider<select name="providerId" defaultValue={service?.providerId} disabled={Boolean(service)}>{providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{service&&<input type="hidden" name="providerId" value={service.providerId}/>}<label>Service<select name="serviceSlug" defaultValue={service?.serviceSlug} disabled={Boolean(service)}>{Object.entries(serviceNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label>{service&&<input type="hidden" name="serviceSlug" value={service.serviceSlug}/>}<div className="form-grid"><label>Duration<input type="number" name="durationMinutes" min="5" max="1440" defaultValue={service?.durationMinutes||60}/></label><label>Before buffer<input type="number" name="bufferBeforeMinutes" min="0" max="480" defaultValue={service?.bufferBeforeMinutes||0}/></label><label>After buffer<input type="number" name="bufferAfterMinutes" min="0" max="480" defaultValue={service?.bufferAfterMinutes||0}/></label><label>Capacity<input type="number" name="capacity" min="1" max="100" defaultValue={service?.capacity||1}/></label></div><label>Booking mode<select name="bookingMode" defaultValue={service?.bookingMode||'REQUEST'}><option>REQUEST</option><option>INSTANT</option></select></label><fieldset><legend>Allowed locations</legend>{locationModes.map(m=><label className="check" key={m}><input type="checkbox" name={`location_${m}`} defaultChecked={service?.allowedLocationModes.includes(m)??m==='ONLINE'}/>{m.replaceAll('_',' ')}</label>)}</fieldset><label className="check"><input name="active" type="checkbox" defaultChecked={service?.active??true}/> Active</label><button>Save assignment</button></form>}

function Availability({data,submit,mutate}:{data:Dashboard;submit:Submit;mutate:(p:Record<string,unknown>)=>Promise<void>}){return <section className="admin-panel"><PanelTitle title="Weekly hours" text="Recurring local availability. Multiple windows per day are supported."/>{data.providers.length?<form className="admin-inline" onSubmit={e=>submit(e,'rule-save',v=>({...v,dayOfWeek:Number(v.dayOfWeek),capacity:Number(v.capacity),active:true}))}><ProviderSelect providers={data.providers}/><label>Day<select name="dayOfWeek">{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label><label>Start<input type="time" name="localStartTime" defaultValue="09:00" required/></label><label>End<input type="time" name="localEndTime" defaultValue="17:00" required/></label><label>Timezone<input name="timezone" defaultValue="Asia/Kolkata" required/></label><label>Capacity<input type="number" name="capacity" defaultValue="1" min="1" max="100"/></label><button>Add hours</button></form>:<Empty text="Add a provider first."/>}<RuleList data={data} kind="rule" mutate={mutate}/></section>}

function Exceptions({data,submit,mutate}:{data:Dashboard;submit:Submit;mutate:(p:Record<string,unknown>)=>Promise<void>}){return <section className="admin-panel"><PanelTitle title="Date exceptions" text="Block a date or replace weekly hours with a custom window."/>{data.providers.length?<form className="admin-inline" onSubmit={e=>submit(e,'exception-save',v=>({...v,capacity:v.capacity?Number(v.capacity):undefined}))}><ProviderSelect providers={data.providers}/><label>Date<input type="date" name="localDate" required/></label><label>Exception<select name="type"><option>UNAVAILABLE</option><option>CUSTOM_HOURS</option></select></label><label>Custom start<input type="time" name="localStartTime"/></label><label>Custom end<input type="time" name="localEndTime"/></label><label>Capacity<input type="number" name="capacity" min="1" max="100"/></label><button>Save exception</button></form>:<Empty text="Add a provider first."/>}<RuleList data={data} kind="exception" mutate={mutate}/></section>}
function ProviderSelect({providers}:{providers:Provider[]}){return <label>Provider<select name="providerId">{providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>}
function RuleList({data,kind,mutate}:{data:Dashboard;kind:'rule'|'exception';mutate:(p:Record<string,unknown>)=>Promise<void>}){const rows=kind==='rule'?data.rules:data.exceptions;return <div className="rule-list">{rows.map(x=><article key={x.id}><div><b>{data.providers.find(p=>p.id===x.providerId)?.name}</b><span>{kind==='rule'?`${days[(x as Rule).dayOfWeek]} · ${(x as Rule).localStartTime}–${(x as Rule).localEndTime} · capacity ${(x as Rule).capacity}`:`${(x as Exception).localDate} · ${(x as Exception).type==='UNAVAILABLE'?'Unavailable':`${(x as Exception).localStartTime}–${(x as Exception).localEndTime} · capacity ${(x as Exception).capacity||1}`}`}</span></div><button className="danger" onClick={()=>mutate({action:`${kind}-delete`,id:x.id})}>Delete</button></article>)}</div>}
function PanelTitle({title,text}:{title:string;text:string}){return <div className="panel-title"><h2>{title}</h2><p>{text}</p></div>};function Empty({text}:{text:string}){return <p className="admin-empty">{text}</p>}
