import test from 'node:test';
import assert from 'node:assert/strict';
import {generateAvailableSlots, generateBookingReference, initialStatusForMode, providerCanPerform, schedulingServiceBySlug, zonedLocalToInstant, type AvailabilityException, type AvailabilityRule, type ExistingBooking, type Provider, type ProviderService} from '../lib/scheduling.ts';

const provider: Provider = {id:'provider-1',name:'Test Provider',type:'ASTROLOGER',active:true,timezone:'Asia/Kolkata',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};
const service: ProviderService = {...schedulingServiceBySlug('astrology')!,providerId:provider.id,active:true};
const rule: AvailabilityRule = {id:'rule-1',providerId:provider.id,dayOfWeek:1,localStartTime:'09:00',localEndTime:'13:00',timezone:'Asia/Kolkata',capacity:1,active:true};
const date = '2026-09-21';
const slots = (overrides: Partial<Parameters<typeof generateAvailableSlots>[0]> = {}) => generateAvailableSlots({provider,service,date,locationMode:'ONLINE',rules:[rule],exceptions:[],existingBookings:[],...overrides});

test('generates basic slots inside a working window',()=>{const result=slots();assert.equal(result[0].localStartTime,'09:00');assert.ok(result.length>1);});
test('excludes overlap with an existing booking',()=>{const booking:ExistingBooking={providerId:provider.id,requestedStart:zonedLocalToInstant(date,'10:00','Asia/Kolkata').toISOString(),requestedEnd:zonedLocalToInstant(date,'11:00','Asia/Kolkata').toISOString(),status:'CONFIRMED'};assert.ok(!slots({existingBookings:[booking]}).some(slot=>slot.localStartTime==='10:00'));});
test('candidate before-buffer conflicts with an earlier booking',()=>{const buffered={...service,bufferBeforeMinutes:15};const booking:ExistingBooking={providerId:provider.id,requestedStart:zonedLocalToInstant(date,'09:00','Asia/Kolkata').toISOString(),requestedEnd:zonedLocalToInstant(date,'09:30','Asia/Kolkata').toISOString(),status:'CONFIRMED'};assert.ok(!slots({service:buffered,existingBookings:[booking]}).some(slot=>slot.localStartTime==='09:30'));});
test('existing after-buffer blocks the following slot',()=>{const booking:ExistingBooking={providerId:provider.id,requestedStart:zonedLocalToInstant(date,'09:00','Asia/Kolkata').toISOString(),requestedEnd:zonedLocalToInstant(date,'09:30','Asia/Kolkata').toISOString(),status:'CONFIRMED',bufferAfterMinutes:10};assert.ok(!slots({existingBookings:[booking]}).some(slot=>slot.localStartTime==='09:30'));});
test('supports long ceremony durations and buffers',()=>{const ceremony:ProviderService={...service,durationMinutes:180,bufferBeforeMinutes:30,bufferAfterMinutes:30};assert.equal(slots({service:ceremony}).length,1);});
test('unavailable exception closes the date',()=>{const exception:AvailabilityException={id:'e1',providerId:provider.id,localDate:date,type:'UNAVAILABLE'};assert.deepEqual(slots({exceptions:[exception]}),[]);});
test('custom-hours exception replaces weekly hours',()=>{const exception:AvailabilityException={id:'e2',providerId:provider.id,localDate:date,type:'CUSTOM_HOURS',localStartTime:'15:00',localEndTime:'16:00'};assert.equal(slots({exceptions:[exception]})[0].localStartTime,'15:00');});
test('capacity greater than one retains remaining capacity',()=>{const capacityService={...service,capacity:2};const capacityRule={...rule,capacity:2};const booking:ExistingBooking={providerId:provider.id,requestedStart:zonedLocalToInstant(date,'09:00','Asia/Kolkata').toISOString(),requestedEnd:zonedLocalToInstant(date,'09:30','Asia/Kolkata').toISOString(),status:'CONFIRMED'};assert.equal(slots({service:capacityService,rules:[capacityRule],existingBookings:[booking]})[0].remainingCapacity,1);});
test('checks provider and service eligibility',()=>{assert.equal(providerCanPerform(provider,[service],'astrology'),true);assert.equal(providerCanPerform(provider,[service],'marriage'),false);});
test('rejects invalid service and date',()=>{assert.equal(schedulingServiceBySlug('special-prasad'),undefined);assert.throws(()=>slots({date:'2026-02-30'}),/Invalid date/);});
test('preserves timezone across an absolute date boundary',()=>{assert.equal(zonedLocalToInstant('2026-09-21','00:15','Asia/Kolkata').toISOString(),'2026-09-20T18:45:00.000Z');});
test('maps request and instant booking modes to correct initial statuses',()=>{assert.equal(initialStatusForMode('REQUEST'),'REQUESTED');assert.equal(initialStatusForMode('INSTANT'),'CONFIRMED');});
test('capacity one fails closed after a confirmed concurrent winner',()=>{const booking:ExistingBooking={providerId:provider.id,requestedStart:zonedLocalToInstant(date,'09:00','Asia/Kolkata').toISOString(),requestedEnd:zonedLocalToInstant(date,'09:30','Asia/Kolkata').toISOString(),status:'CONFIRMED'};assert.ok(!slots({existingBookings:[booking]}).some(slot=>slot.localStartTime==='09:00'));});
test('creates human-readable non-sequential references',()=>{assert.match(generateBookingReference(new Date('2026-09-15T00:00:00Z'),new Uint8Array([1,2,3])),/^SHU-260915-[A-Z2-9]{4}$/);});
