'use client';
import {useEffect,useState} from 'react';
import type {AdminPuja} from '../../../lib/puja-repository';
const blank={name:'',slug:'',shortDescription:'',fullDescription:'',durationMinutes:'',startingPriceRupees:'',samagriRequired:false,samagriAvailable:false,onlineAvailable:false,templeAvailable:false,notes:'',active:false};
const slugify=(v:string)=>v.toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const money=(v:number|null)=>v===null?'Price not set':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
export default function PujaManager(){
 const[items,setItems]=useState<AdminPuja[]>([]),[form,setForm]=useState<Record<string,unknown>>(blank),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));
 async function load(){const r=await fetch('/api/admin/pujas',{cache:'no-store'}),d=await r.json();r.ok?setItems(d.pujas):setMessage(d.message)}
 useEffect(()=>{load()},[]);
 function edit(p:AdminPuja){setEditing(p.id);setForm({...p,durationMinutes:p.durationMinutes??'',startingPriceRupees:p.startingPriceRupees??''});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');const r=await fetch('/api/admin/pujas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:editing})}),d=await r.json();setBusy(false);if(!r.ok){setMessage(d.message);return}setEditing(null);setForm(blank);const translated=d.puja.translationStatus==='COMPLETED'?' Hindi and Odia translations are ready.':' English was saved; translation needs retrying.';setMessage((editing?'Puja and price updated.':'Puja added as a draft.')+translated);await load()}
 return <main className="admin-shell"><header className="admin-top"><div><img src="/shuvamstu-logo.jpg" alt="Shuvamstu"/><span>Puja catalogue</span></div></header><div className="admin-body"><section className="admin-heading"><div><p className="admin-eyebrow">Catalogue management</p><h1>{editing?'Edit puja':'Add a puja'}</h1><p>New pujas stay private until you publish them.</p></div></section>{message&&<p className="admin-notice" role="status">{message}</p>}<form className="admin-panel puja-form" onSubmit={save}><div className="form-grid"><label>Name<input required value={String(form.name)} onChange={e=>{set('name',e.target.value);if(!editing)set('slug',slugify(e.target.value))}}/></label><label>URL slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={String(form.slug)} onChange={e=>set('slug',slugify(e.target.value))}/></label><label>Duration (minutes)<input type="number" min="1" max="1440" value={String(form.durationMinutes)} onChange={e=>set('durationMinutes',e.target.value)}/></label><label>Starting price (₹)<input type="number" min="0" step="1" placeholder="Leave empty for request a quote" value={String(form.startingPriceRupees)} onChange={e=>set('startingPriceRupees',e.target.value)}/><small>Leave empty when the price must be confirmed manually.</small></label></div><label>Short description<textarea maxLength={500} value={String(form.shortDescription)} onChange={e=>set('shortDescription',e.target.value)}/></label><label>Full description<textarea rows={5} maxLength={10000} value={String(form.fullDescription)} onChange={e=>set('fullDescription',e.target.value)}/></label><div className="puja-checks">{[['samagriRequired','Samagri required'],['samagriAvailable','Samagri kit available'],['onlineAvailable','Online available'],['templeAvailable','Temple available'],['active','Published']].map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={Boolean(form[k])} onChange={e=>set(k,e.target.checked)}/>{l}</label>)}</div><label>Internal notes<textarea rows={3} maxLength={3000} value={String(form.notes)} onChange={e=>set('notes',e.target.value)}/></label><div className="form-actions">{editing&&<button type="button" className="admin-quiet" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}<button disabled={busy}>{busy?'Saving…':editing?'Save changes':'Add puja'}</button></div></form><section className="admin-panel puja-list"><h2>All pujas ({items.length})</h2>{items.map(p=><article key={p.id}><div><b>{p.name}</b><small>/{p.slug} · {p.active?'Published':'Draft / paused'} · {money(p.startingPriceRupees)}</small></div><button onClick={()=>edit(p)}>Edit</button></article>)}</section></div></main>
}
