'use client';
import Link from 'next/link';
import {dictionary} from '../lib/i18n';
import {LanguageToggle,useLocale} from './language-toggle';

const navigation=[['pujas','/pujas'],['pujaris','/pujaris'],['astrologers','/astrologers'],['numerologists','/numerologists'],['about','/about'],['support','/contact']] as const;

export function Header(){const[locale,setLocale]=useLocale(),t=dictionary(locale);return <header className="site-header"><div className="wrap nav"><Link className="brand" href="/" aria-label="Shuvamstu home"><img src="/shuvamstu-logo.jpg" alt="Shuvamstu — trusted religious services"/></Link><nav className="desktop-links" aria-label="Primary">{navigation.map(([key,href])=><Link key={href} href={href}>{t[key]}</Link>)}<LanguageToggle locale={locale} label={t.language} onChange={setLocale}/><Link className="nav-cta" href="/book">{t.book} <span aria-hidden="true">→</span></Link></nav><details className="mobile-menu"><summary aria-label="Open navigation">{t.menu}</summary><nav aria-label="Mobile navigation">{navigation.map(([key,href])=><Link key={href} href={href}>{t[key]}</Link>)}<LanguageToggle locale={locale} label={t.language} onChange={setLocale}/><Link href="/book">{t.book}</Link></nav></details></div></header>}
export function Footer(){const[locale]=useLocale(),t=dictionary(locale);return <footer><div className="wrap footer-grid"><div className="footer-brand"><img src="/shuvamstu-logo-transparent.png" alt="Shuvamstu — trusted religious services"/><p>{t.footer}</p></div><div><strong>{t.services}</strong><Link href="/pujas">{t.browsePujas}</Link><Link href="/pujaris">{t.findPujari}</Link><Link href="/astrologers">{t.astrologers}</Link><Link href="/numerologists">{t.numerologists}</Link><Link href="/book">{t.startBooking}</Link></div><div><strong>Shuvamstu</strong><Link href="/about">{t.aboutUs}</Link><Link href="/contact">{t.contact}</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of service</Link><Link href="/cancellation">Cancellation & refunds</Link><Link href="/account">{t.bookings}</Link><Link href="/pujari">{t.pujariLogin}</Link><Link href="/admin">{t.dashboard}</Link></div></div><div className="wrap footer-bottom">© {new Date().getFullYear()} Shuvamstu. {t.rights}</div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
