'use client';
import {useEffect} from 'react';
import {usePathname} from 'next/navigation';
import {isLocale,LOCALE_COOKIE} from '../lib/i18n';
const excludedPaths=['/account','/admin','/booking','/pujari','/pujas'];
const translated=new WeakSet<Node>();
const latin=/[A-Za-z]{2}/;
function locale(){const value=document.cookie.split('; ').find(item=>item.startsWith(`${LOCALE_COOKIE}=`))?.split('=')[1];return isLocale(value)?value:'en-IN'}
function excluded(element:Element|null){return !element||Boolean(element.closest('.site-header,footer,[data-localized],script,style,code,pre,[contenteditable="true"]'))}
function collect(){const nodes:Text[]=[],attributes:{element:Element;name:string;source:string}[]=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const node=walker.currentNode as Text,source=node.data.trim();if(!translated.has(node)&&latin.test(source)&&!excluded(node.parentElement))nodes.push(node)}document.querySelectorAll('input[placeholder],textarea[placeholder],[title],[aria-label]').forEach(element=>{for(const name of ['placeholder','title','aria-label']){const source=element.getAttribute(name)?.trim();if(source&&latin.test(source)&&!excluded(element))attributes.push({element,name,source})}});return{nodes,attributes}}
export function PageTranslator(){const pathname=usePathname();useEffect(()=>{const excludedPath=excludedPaths.some(path=>pathname===path||pathname.startsWith(`${path}/`));if(locale()==='en-IN'||excludedPath)return;let stopped=false,timer:ReturnType<typeof setTimeout>;async function run(){const{nodes,attributes}=collect(),sources=[...new Set([...nodes.map(node=>node.data.trim()),...attributes.map(item=>item.source)])].slice(0,25);if(!sources.length)return;const response=await fetch('/api/translations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texts:sources})});if(!response.ok||stopped)return;const{translations}=await response.json() as {translations:Record<string,string>};nodes.forEach(node=>{const source=node.data.trim(),value=translations[source];if(value){node.data=node.data.replace(source,value);translated.add(node)}});attributes.forEach(({element,name,source})=>{if(translations[source])element.setAttribute(name,translations[source])})}const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,120)});run();observer.observe(document.body,{childList:true,subtree:true});return()=>{stopped=true;clearTimeout(timer);observer.disconnect()}},[pathname]);return null}
