import Link from 'next/link';
import {Shell} from './components';

const popular=[
  ['Gruha Pratistha','A complete house ceremony with clear preparation guidance.','₹3,100 onwards','/pujas/gruha-pratistha'],
  ['Satyanarayana Puja','A thoughtfully coordinated puja for home and family.','₹2,100 onwards','/pujas/satyanarayana-puja'],
  ['Rudrabhisek','Book an experienced Pujari for Rudrabhisek at home or temple.','₹2,500 onwards','/pujas/rudrabhisek'],
] as const;

export default function Home(){return <Shell><main>
  <section className="hero marketplace-hero"><div className="wrap hero-inner"><div className="hero-panel marketplace-panel"><span className="kicker light">Now serving Odisha</span><h1>Trusted Religious Services, Made Simple.</h1><p>Book verified Pujaris for your important rituals with transparent pricing, convenient scheduling and optional samagri.</p><div className="actions"><Link className="btn" href="/book">Book a Puja <span aria-hidden="true">→</span></Link><Link className="btn btn-outline" href="/pujaris">Find a Pujari</Link></div><div className="trust-row"><span>✓ Verified Pujaris</span><span>✓ Transparent pricing</span><span>✓ Samagri available</span></div></div></div></section>
  <section className="quick-start"><div className="wrap quick-start-inner"><div><span className="kicker">Plan your puja</span><h2>What would you like to book?</h2></div><form action="/book"><label><span>Puja</span><select name="puja" defaultValue="gruha-pratistha"><option value="gruha-pratistha">Gruha Pratistha</option><option value="satyanarayana-puja">Satyanarayana Puja</option><option value="rudrabhisek">Rudrabhisek</option><option value="ganapati-puja">Ganapati Puja</option></select></label><label><span>City</span><select name="city" defaultValue="bhubaneswar"><option value="dhenkanal">Dhenkanal</option><option value="bhubaneswar">Bhubaneswar</option><option value="cuttack">Cuttack</option></select></label><button className="btn">See available Pujaris →</button></form></div></section>
  <section className="section"><div className="wrap"><div className="section-head"><span className="kicker">Popular pujas</span><h2>Choose with confidence</h2><p>Every package shows what is included, how long it usually takes, and the complete price before you book.</p></div><div className="service-grid marketplace-cards">{popular.map(([name,description,price,href])=><Link className="service-card" href={href} key={name}><span className="service-icon" aria-hidden="true">ॐ</span><div><h3>{name}</h3><p>{description}</p><strong className="price-from">{price}</strong><span className="card-link">View packages →</span></div></Link>)}</div><div className="center-action"><Link className="text-link" href="/pujas">View all pujas →</Link></div></div></section>
  <section className="services-section section" id="how-it-works"><div className="wrap"><div className="section-head centered"><span className="kicker">How it works</span><h2>A dependable puja, without the uncertainty</h2></div><div className="process-grid"><article><b>01</b><h3>Tell us what you need</h3><p>Choose the puja, city, language, date and preferred time.</p></article><article><b>02</b><h3>Choose a verified Pujari</h3><p>Compare suitable Pujaris, packages and clear pricing.</p></article><article><b>03</b><h3>We coordinate the details</h3><p>Track confirmation, samagri and service progress in one place.</p></article></div></div></section>
  <section className="section"><div className="wrap"><div className="section-head centered"><span className="kicker">Consultations</span><h2>Astrology and Numerology guidance</h2><p>Shuvamstu also connects customers with published Astrologers and Numerologists already available on the platform.</p></div><div className="service-grid consultation-grid"><Link className="service-card" href="/astrologers"><span className="service-icon" aria-hidden="true">✦</span><h3>Astrologers</h3><p>Explore published profiles for traditional astrology consultations and life-event guidance.</p><span className="card-link">Find an Astrologer →</span></Link><Link className="service-card" href="/numerologists"><span className="service-icon" aria-hidden="true">9</span><h3>Numerologists</h3><p>Connect with published Numerologists for name and birth-date consultations.</p><span className="card-link">Find a Numerologist →</span></Link></div></div></section>
  <section className="trust-section section"><div className="wrap split"><div><span className="kicker">Verified by Shuvamstu</span><h2>Trust is part of the service.</h2><p className="lead">Profiles are reviewed before a verification badge appears. If plans change, Shuvamstu helps coordinate an alternative so your booking stays protected.</p><Link className="btn" href="/pujaris">Meet our Pujaris</Link></div><div className="trust-card"><div className="verified-seal">✓</div><h3>Clear at every step</h3><ul><li>Experience, languages and specializations</li><li>Availability matched to your time</li><li>Itemized service and samagri pricing</li><li>Founder-supported booking coordination</li></ul></div></div></section>
  <section className="online-banner"><div className="wrap online-inner"><div><span className="kicker light">Your choice</span><h2>In-person, online or at a temple.</h2><p>Choose the format that works for your family. Online pujas use a secure external meeting link—no new app required.</p></div><Link className="btn btn-light" href="/book?mode=ONLINE">Explore online puja →</Link></div></section>
  <section className="section"><div className="wrap"><div className="section-head centered"><span className="kicker">Cities served</span><h2>Starting in Odisha, city by city</h2><p>Dhenkanal is our founding market, with service expanding across Bhubaneswar and Cuttack.</p></div><div className="city-grid"><article><b>Dhenkanal</b><span>Founding market</span></article><article><b>Bhubaneswar</b><span>Now onboarding</span></article><article><b>Cuttack</b><span>Now onboarding</span></article></div></div></section>
  <section className="closing"><div className="wrap"><span className="kicker light">Shuvamstu</span><h2>Plan your puja with confidence.</h2><p>Choose a service now, or speak with us if you need help deciding.</p><div className="actions centered-actions"><Link className="btn btn-dark" href="/book">Book a Puja →</Link><Link className="btn btn-outline" href="/contact">Get help</Link></div></div></section>
  </main></Shell>}
