export const LOCALE_COOKIE='shuvamstu_locale';
export const locales=['en-IN','hi-IN','od-IN'] as const;
export type Locale=(typeof locales)[number];
export function isLocale(value:unknown):value is Locale{return typeof value==='string'&&locales.includes(value as Locale)}
const messages={
 'en-IN':{pujas:'Pujas',pujaris:'Pujaris',astrologers:'Astrologers',numerologists:'Numerologists',about:'About',support:'Support',book:'Book a Puja',menu:'Menu',language:'Language',services:'Services',browsePujas:'Browse pujas',findPujari:'Find a Pujari',startBooking:'Start booking',aboutUs:'About us',contact:'Contact & support',bookings:'My bookings',pujariLogin:'Pujari login',dashboard:'Founder dashboard',footer:'Book verified Pujaris and connect with Astrologers or Numerologists through one trusted platform.',rights:'All rights reserved.',catalogue:'Puja catalogue',findPuja:'Find the right puja for your occasion',browse:'Browse all {count} available pujas. Configured packages show pricing; other services are confirmed after we understand your requirements.',allPujas:'All {count} pujas',packages:'Configured packages',online:'Online available',samagri:'Samagri option',priceLater:'Price confirmed after details',from:'From',details:'View details',service:'Puja service',aboutService:'About this service',traditions:'Traditions and requirements can vary by family and Pujari. Your selected Pujari confirms the ritual plan before service.',helps:'How Shuvamstu helps',matched:'A suitable verified Pujari matched to your city and language',requirements:'Requirements and preparation confirmed before booking',duration:'Typical duration',updates:'Booking coordination and status updates',samagriSupport:'Optional samagri support',participate:'Ways to participate',inPerson:'In person',temple:'At a temple',configured:'Configured package',personalized:'Personalized requirement',quote:'Request a quote',samagriFrom:'Samagri option from',finalPrice:'Final price is itemized before confirmation.',confirmPrice:'We will confirm scope, availability and the complete price before you commit.',availability:'Check availability',share:'Share requirements'},
 'hi-IN':{pujas:'पूजाएँ',pujaris:'पुजारी',astrologers:'ज्योतिषी',numerologists:'अंकशास्त्री',about:'हमारे बारे में',support:'सहायता',book:'पूजा बुक करें',menu:'मेन्यू',language:'भाषा',services:'सेवाएँ',browsePujas:'पूजाएँ देखें',findPujari:'पुजारी खोजें',startBooking:'बुकिंग शुरू करें',aboutUs:'हमारे बारे में',contact:'संपर्क और सहायता',bookings:'मेरी बुकिंग',pujariLogin:'पुजारी लॉगिन',dashboard:'फाउंडर डैशबोर्ड',footer:'एक विश्वसनीय मंच पर सत्यापित पुजारियों को बुक करें और ज्योतिषियों या अंकशास्त्रियों से जुड़ें।',rights:'सर्वाधिकार सुरक्षित।',catalogue:'पूजा सूची',findPuja:'अपने अवसर के लिए सही पूजा खोजें',browse:'सभी {count} उपलब्ध पूजाएँ देखें। निर्धारित पैकेज में मूल्य दिखते हैं; अन्य सेवाएँ आपकी आवश्यकताएँ समझने के बाद तय की जाती हैं।',allPujas:'सभी {count} पूजाएँ',packages:'निर्धारित पैकेज',online:'ऑनलाइन उपलब्ध',samagri:'सामग्री विकल्प',priceLater:'विवरण के बाद मूल्य की पुष्टि',from:'से शुरू',details:'विवरण देखें',service:'पूजा सेवा',aboutService:'इस सेवा के बारे में',traditions:'परंपराएँ और आवश्यकताएँ परिवार व पुजारी के अनुसार बदल सकती हैं। चयनित पुजारी सेवा से पहले अनुष्ठान योजना की पुष्टि करेंगे।',helps:'शुभमस्तु कैसे मदद करता है',matched:'आपके शहर और भाषा के अनुसार उपयुक्त सत्यापित पुजारी',requirements:'बुकिंग से पहले आवश्यकताओं और तैयारी की पुष्टि',duration:'सामान्य अवधि',updates:'बुकिंग समन्वय और स्थिति अपडेट',samagriSupport:'वैकल्पिक सामग्री सहायता',participate:'भाग लेने के तरीके',inPerson:'व्यक्तिगत रूप से',temple:'मंदिर में',configured:'निर्धारित पैकेज',personalized:'व्यक्तिगत आवश्यकता',quote:'मूल्य का अनुरोध करें',samagriFrom:'सामग्री विकल्प शुरू',finalPrice:'पुष्टि से पहले अंतिम मूल्य का पूरा विवरण दिया जाता है।',confirmPrice:'आपकी सहमति से पहले हम कार्यक्षेत्र, उपलब्धता और पूरे मूल्य की पुष्टि करेंगे।',availability:'उपलब्धता जाँचें',share:'आवश्यकताएँ साझा करें'},
 'od-IN':{pujas:'ପୂଜା',pujaris:'ପୂଜାରୀ',astrologers:'ଜ୍ୟୋତିଷ',numerologists:'ସଂଖ୍ୟାବିଦ୍',about:'ଆମ ବିଷୟରେ',support:'ସହାୟତା',book:'ପୂଜା ବୁକ୍ କରନ୍ତୁ',menu:'ମେନୁ',language:'ଭାଷା',services:'ସେବା',browsePujas:'ପୂଜା ଦେଖନ୍ତୁ',findPujari:'ପୂଜାରୀ ଖୋଜନ୍ତୁ',startBooking:'ବୁକିଂ ଆରମ୍ଭ କରନ୍ତୁ',aboutUs:'ଆମ ବିଷୟରେ',contact:'ଯୋଗାଯୋଗ ଓ ସହାୟତା',bookings:'ମୋ ବୁକିଂ',pujariLogin:'ପୂଜାରୀ ଲଗଇନ୍',dashboard:'ଫାଉଣ୍ଡର ଡ୍ୟାସବୋର୍ଡ',footer:'ଗୋଟିଏ ବିଶ୍ୱସ୍ତ ପ୍ଲାଟଫର୍ମରେ ଯାଞ୍ଚ ହୋଇଥିବା ପୂଜାରୀଙ୍କୁ ବୁକ୍ କରନ୍ତୁ ଏବଂ ଜ୍ୟୋତିଷ ବା ସଂଖ୍ୟାବିଦ୍‌ଙ୍କ ସହ ଯୋଡ଼ି ହୁଅନ୍ତୁ।',rights:'ସର୍ବସ୍ୱତ୍ୱ ସଂରକ୍ଷିତ।',catalogue:'ପୂଜା ତାଲିକା',findPuja:'ଆପଣଙ୍କ ଅବସର ପାଇଁ ଉପଯୁକ୍ତ ପୂଜା ଖୋଜନ୍ତୁ',browse:'ସମସ୍ତ {count}ଟି ଉପଲବ୍ଧ ପୂଜା ଦେଖନ୍ତୁ। ନିର୍ଦ୍ଧାରିତ ପ୍ୟାକେଜରେ ମୂଲ୍ୟ ଦିଆଯାଇଛି; ଅନ୍ୟ ସେବା ଆପଣଙ୍କ ଆବଶ୍ୟକତା ବୁଝିବା ପରେ ନିଶ୍ଚିତ ହୁଏ।',allPujas:'ସମସ୍ତ {count}ଟି ପୂଜା',packages:'ନିର୍ଦ୍ଧାରିତ ପ୍ୟାକେଜ',online:'ଅନଲାଇନ୍ ଉପଲବ୍ଧ',samagri:'ସାମଗ୍ରୀ ବିକଳ୍ପ',priceLater:'ବିବରଣୀ ପରେ ମୂଲ୍ୟ ନିଶ୍ଚିତ',from:'ଆରମ୍ଭ',details:'ବିବରଣୀ ଦେଖନ୍ତୁ',service:'ପୂଜା ସେବା',aboutService:'ଏହି ସେବା ବିଷୟରେ',traditions:'ପରିବାର ଓ ପୂଜାରୀଙ୍କ ଅନୁସାରେ ପରମ୍ପରା ଏବଂ ଆବଶ୍ୟକତା ଭିନ୍ନ ହୋଇପାରେ। ସେବା ପୂର୍ବରୁ ଆପଣଙ୍କ ପୂଜାରୀ ପୂଜା ଯୋଜନା ନିଶ୍ଚିତ କରିବେ।',helps:'ଶୁଭମସ୍ତୁ କିପରି ସାହାଯ୍ୟ କରେ',matched:'ଆପଣଙ୍କ ସହର ଓ ଭାଷା ଅନୁଯାୟୀ ଉପଯୁକ୍ତ ଯାଞ୍ଚ ହୋଇଥିବା ପୂଜାରୀ',requirements:'ବୁକିଂ ପୂର୍ବରୁ ଆବଶ୍ୟକତା ଓ ପ୍ରସ୍ତୁତି ନିଶ୍ଚିତ',duration:'ସାଧାରଣ ଅବଧି',updates:'ବୁକିଂ ସମନ୍ୱୟ ଓ ସ୍ଥିତି ଅପଡେଟ୍',samagriSupport:'ଇଚ୍ଛାଧୀନ ସାମଗ୍ରୀ ସହାୟତା',participate:'ଅଂଶଗ୍ରହଣର ଉପାୟ',inPerson:'ସିଧାସଳଖ',temple:'ମନ୍ଦିରରେ',configured:'ନିର୍ଦ୍ଧାରିତ ପ୍ୟାକେଜ',personalized:'ବ୍ୟକ୍ତିଗତ ଆବଶ୍ୟକତା',quote:'ମୂଲ୍ୟ ପଚାରନ୍ତୁ',samagriFrom:'ସାମଗ୍ରୀ ବିକଳ୍ପ ଆରମ୍ଭ',finalPrice:'ନିଶ୍ଚିତକରଣ ପୂର୍ବରୁ ଅନ୍ତିମ ମୂଲ୍ୟର ସବିଶେଷ ତଥ୍ୟ ଦିଆଯାଏ।',confirmPrice:'ଆପଣ ସମ୍ମତି ଦେବା ପୂର୍ବରୁ ଆମେ କାର୍ଯ୍ୟ, ଉପଲବ୍ଧତା ଓ ସମ୍ପୂର୍ଣ୍ଣ ମୂଲ୍ୟ ନିଶ୍ଚିତ କରିବୁ।',availability:'ଉପଲବ୍ଧତା ଦେଖନ୍ତୁ',share:'ଆବଶ୍ୟକତା ଜଣାନ୍ତୁ'},
} as const;
export function dictionary(locale:Locale){return messages[locale]}
export function interpolate(value:string,variables:Record<string,string|number>){return value.replace(/\{(\w+)\}/g,(_,key)=>String(variables[key]??''))}
