'use client';
import {FormEvent,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Shell} from '../components';
import {services} from '../data/services';
import {pujaCategories} from '../data/puja-categories';

type SubmissionState='idle'|'submitting'|'success'|'error';
export default function Enquiry(){
 const query=useSearchParams(),requestedService=query.get('service')||'',initialService=services.some(({slug})=>slug===requestedService)?requestedService:'',requestedPuja=query.get('puja')||'',initialPuja=pujaCategories.includes(requestedPuja as typeof pujaCategories[number])?requestedPuja:'',practitioner=(query.get('practitioner')||'').slice(0,100);
 const [service,setService]=useState(initialService),[state,setState]=useState<SubmissionState>('idle'),[status,setStatus]=useState('');const submitting=useRef(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting.current)return;const form=event.currentTarget,fields=new FormData(form);submitting.current=true;setState('submitting');setStatus('Submitting your enquiry…');try{const response=await fetch('/api/enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fields.get('name'),phone:fields.get('phone'),email:fields.get('email'),service:fields.get('service'),pujaCategory:fields.get('pujaCategory'),preferredDate:fields.get('preferredDate'),message:fields.get('message')})}),result:{message?:string}=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||'We could not submit your enquiry. Please try again later.');form.reset();setService('');setState('success');setStatus('Thank you. Your enquiry has been received.')}catch(error){setState('error');setStatus(error instanceof Error?error.message:'We could not submit your enquiry. Please try again later.')}finally{submitting.current=false}}
 return <Shell><main><section className="plain-hero compact"><div className="wrap narrow"><span className="kicker">Enquiry</span><h1>Tell us about the occasion.</h1><p className="lead">Share the details you know. We will use your phone number to coordinate the next step.</p></div></section><section className="section"><div className="wrap form-wrap"><form className="enquiry-form" onSubmit={submit}><label>Your name<input name="name" required maxLength={100} autoComplete="name" placeholder="Name"/></label><label>Phone number<input name="phone" type="tel" required minLength={9} maxLength={30} autoComplete="tel" placeholder="+91 98765 43210"/></label><label>Email <span>(optional)</span><input name="email" type="email" maxLength={254} autoComplete="email" placeholder="you@example.com"/></label><label>Service<select name="service" value={service} onChange={event=>setService(event.target.value)}><option value="">Choose a service</option>{services.map(item=><option key={item.slug} value={item.slug}>{item.title}</option>)}</select></label>{service==='puja-rituals'&&<label>Puja category<select name="pujaCategory" defaultValue={initialPuja} required><option value="">Choose a Puja</option>{pujaCategories.map(puja=><option key={puja}>{puja}</option>)}</select></label>}<label>Preferred date<input name="preferredDate" type="date"/></label><label className="full">Tell us about the occasion<textarea name="message" maxLength={2000} rows={6} defaultValue={practitioner?`I would like to enquire with ${practitioner}.\n\n`:''} placeholder="Occasion, location, family tradition or anything else that may help..."/></label><button className="btn full-button" type="submit" disabled={state==='submitting'}>{state==='submitting'?'Submitting…':'Submit enquiry'}</button>{status&&<p className={`full form-status ${state}`} role={state==='error'?'alert':'status'} aria-live="polite">{status}</p>}</form></div></section></main></Shell>;
}
