import {NextRequest,NextResponse} from 'next/server';
import {authorizedRequest,sameOrigin} from '../../../lib/admin-auth';
import {convertEnquiryToBooking,deleteException,deleteRule,getAdminDashboard,getBookingSchedulingConfig,rescheduleBooking,saveException,saveProvider,saveProviderService,saveRule,updateBookingStatus,updateEnquiryStatus} from '../../../lib/admin-repository';
import {isValidLocalDate,zonedLocalToInstant,type LocationMode} from '../../../lib/scheduling';
import {sendBookingNotification} from '../../../lib/booking-notifications';

const statuses=['REQUESTED','PENDING_CONFIRMATION','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED'];
const services=['astrology','numerology','online-puja','puja-rituals','bratopanayan','marriage'];
const locations=['ONLINE','CUSTOMER_LOCATION','TEMPLE','OFFICE'];
const time=/^([01]\d|2[0-3]):[0-5]\d$/; const date=/^\d{4}-\d{2}-\d{2}$/;
const text=(v:unknown,max=100)=>typeof v==='string'&&v.trim()&&v.trim().length<=max?v.trim():null;
const integer=(v:unknown,min:number,max:number)=>Number.isInteger(v)&&Number(v)>=min&&Number(v)<=max?Number(v):null;
function timezone(value:unknown){const v=text(value,80);if(!v)return null;try{new Intl.DateTimeFormat('en',{timeZone:v}).format();return v}catch{return null}}
function unauthorized(){return NextResponse.json({message:'Sign in required.'},{status:401})}

export async function GET(request:NextRequest){if(!authorizedRequest(request))return unauthorized();try{return NextResponse.json(await getAdminDashboard(),{headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({message:'Admin database is unavailable. Check DATABASE_URL and apply the scheduling migration.'},{status:503})}}

export async function POST(request:NextRequest){
  if(!authorizedRequest(request))return unauthorized();
  if(!sameOrigin(request))return NextResponse.json({message:'Invalid request origin.'},{status:403});
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null;
  if(!body||typeof body.action!=='string')return NextResponse.json({message:'Invalid admin action.'},{status:400});
  try{
    if(body.action==='booking-status'){const id=text(body.id,30),status=text(body.status,30),adminNotes=body.adminNotes?text(body.adminNotes,2000):'',meetingUrl=body.meetingUrl?text(body.meetingUrl,500):'';if(!id||!status||!/^\d+$/.test(id)||!statuses.includes(status)||(meetingUrl&&!/^https:\/\//i.test(meetingUrl)))throw new Error('VALIDATION');const updated=await updateBookingStatus(id,status,adminNotes||'',meetingUrl||'');await sendBookingNotification('BOOKING_STATUS_UPDATED',updated)}
    else if(body.action==='enquiry-status'){const id=text(body.id,30),status=text(body.status,20);if(!id||!/^\d+$/.test(id)||!status||!['NEW','CONTACTED','CLOSED'].includes(status))throw new Error('VALIDATION');await updateEnquiryStatus(id,status)}
    else if(body.action==='enquiry-convert'){const enquiryId=text(body.enquiryId,30),providerId=text(body.providerId,100),localDate=text(body.localDate,10),localTime=text(body.localTime,5),locationMode=text(body.locationMode,40),venue=body.venue?text(body.venue,500):'';if(!enquiryId||!/^\d+$/.test(enquiryId)||!providerId||!localDate||!isValidLocalDate(localDate)||!localTime||!time.test(localTime)||!locationMode||!locations.includes(locationMode)||(body.venue&&!venue))throw new Error('VALIDATION');const converted=await convertEnquiryToBooking({enquiryId,providerId,localDate,localTime,locationMode:locationMode as LocationMode,venue:venue||''});const manageUrl=converted.manageToken?new URL('/booking/manage',process.env.PUBLIC_SITE_URL||request.url):null;if(manageUrl){manageUrl.searchParams.set('reference',converted.reference);manageUrl.searchParams.set('token',converted.manageToken!)}const booking={...converted,manageToken:undefined,manageUrl:manageUrl?.toString()||null};if(converted.created)await sendBookingNotification('ENQUIRY_CONVERTED_TO_BOOKING',booking);return NextResponse.json({ok:true,booking},{status:converted.created?201:200,headers:{'Cache-Control':'no-store'}})}
    else if(body.action==='booking-reschedule'){const id=text(body.id,30),localDate=text(body.localDate,10),localTime=text(body.localTime,5),status=text(body.status,30);if(!id||!/^\d+$/.test(id)||!localDate||!isValidLocalDate(localDate)||!localTime||!time.test(localTime)||!status||!statuses.includes(status))throw new Error('VALIDATION');const config=await getBookingSchedulingConfig(id);if(!config)throw new Error('BOOKING_NOT_FOUND');const requestedStart=zonedLocalToInstant(localDate,localTime,config.timezone),requestedEnd=new Date(requestedStart.getTime()+config.durationMinutes*60000);const updated=await rescheduleBooking({id,localDate,localTime,requestedStart:requestedStart.toISOString(),requestedEnd:requestedEnd.toISOString(),status});await sendBookingNotification('BOOKING_RESCHEDULED',updated)}
    else if(body.action==='provider-save'){const id=body.id?text(body.id,100):undefined;const name=text(body.name,100);const type=body.type;const zone=timezone(body.timezone);const slug=body.slug?text(body.slug,80):'';const bio=body.bio?text(body.bio,3000):'';const city=body.city?text(body.city,100):'';const qualifications=body.qualifications?text(body.qualifications,500):'';const photoUrl=body.photoUrl?text(body.photoUrl,500):'';const experienceYears=body.experienceYears===''||body.experienceYears===null?null:integer(body.experienceYears,0,100);const languages=Array.isArray(body.languages)?body.languages.filter(v=>typeof v==='string'&&v.trim()).map(v=>String(v).trim()).slice(0,20):[];const specialties=Array.isArray(body.specialties)?body.specialties.filter(v=>typeof v==='string'&&v.trim()).map(v=>String(v).trim()).slice(0,30):[];if(!name||!zone||(type!=='PANDIT'&&type!=='ASTROLOGER'&&type!=='NUMEROLOGIST')||(slug&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))||(body.experienceYears!==''&&body.experienceYears!==null&&experienceYears===null)||(photoUrl&&!/^https:\/\//i.test(photoUrl))||(body.published===true&&(!slug||!bio)))throw new Error('VALIDATION');await saveProvider({id:id||undefined,name,type,timezone:zone,active:body.active!==false,slug:slug||'',bio:bio||'',experienceYears,city:city||'',languages,specialties,qualifications:qualifications||'',photoUrl:photoUrl||'',published:body.published===true})}
    else if(body.action==='service-save'){const providerId=text(body.providerId,100),serviceSlug=text(body.serviceSlug,100),duration=integer(body.durationMinutes,5,1440),before=integer(body.bufferBeforeMinutes,0,480),after=integer(body.bufferAfterMinutes,0,480),capacity=integer(body.capacity,1,100),mode=body.bookingMode;const allowed=Array.isArray(body.allowedLocationModes)?body.allowedLocationModes.filter(v=>typeof v==='string'&&locations.includes(v)):[];if(!providerId||!serviceSlug||!services.includes(serviceSlug)||!duration||before===null||after===null||!capacity||(mode!=='INSTANT'&&mode!=='REQUEST')||!allowed.length)throw new Error('VALIDATION');await saveProviderService({providerId,serviceSlug,durationMinutes:duration,bufferBeforeMinutes:before,bufferAfterMinutes:after,capacity,bookingMode:mode,allowedLocationModes:allowed,active:body.active!==false})}
    else if(body.action==='rule-save'){const id=body.id?text(body.id,100):undefined,providerId=text(body.providerId,100),day=integer(body.dayOfWeek,0,6),start=text(body.localStartTime,5),end=text(body.localEndTime,5),zone=timezone(body.timezone),capacity=integer(body.capacity,1,100);if(!providerId||day===null||!start||!end||!time.test(start)||!time.test(end)||start>=end||!zone||!capacity)throw new Error('VALIDATION');await saveRule({id:id||undefined,providerId,dayOfWeek:day,localStartTime:start,localEndTime:end,timezone:zone,capacity,active:body.active!==false})}
    else if(body.action==='rule-delete'){const id=text(body.id,100);if(!id)throw new Error('VALIDATION');await deleteRule(id)}
    else if(body.action==='exception-save'){const providerId=text(body.providerId,100),localDate=text(body.localDate,10),type=body.type,start=text(body.localStartTime,5)||undefined,end=text(body.localEndTime,5)||undefined,capacity=body.capacity?integer(body.capacity,1,100)||undefined:undefined;if(!providerId||!localDate||!date.test(localDate)||(type!=='UNAVAILABLE'&&type!=='CUSTOM_HOURS')||(type==='CUSTOM_HOURS'&&(!start||!end||!time.test(start)||!time.test(end)||start>=end)))throw new Error('VALIDATION');await saveException({providerId,localDate,type,localStartTime:type==='CUSTOM_HOURS'?start:undefined,localEndTime:type==='CUSTOM_HOURS'?end:undefined,capacity:type==='CUSTOM_HOURS'?capacity:undefined})}
    else if(body.action==='exception-delete'){const id=text(body.id,100);if(!id)throw new Error('VALIDATION');await deleteException(id)}
    else return NextResponse.json({message:'Unknown admin action.'},{status:400});
    return NextResponse.json({ok:true});
  }catch(error){
    const code=error instanceof Error?error.message:'';
    if(code==='SLOT_UNAVAILABLE'||code==='CAPACITY_UNAVAILABLE')return NextResponse.json({message:'That time is no longer available. Choose another slot.'},{status:409});
    if(code==='PROVIDER_NOT_ELIGIBLE')return NextResponse.json({message:'That practitioner is not assigned to this service.'},{status:400});
    if(code==='LOCATION_NOT_ALLOWED')return NextResponse.json({message:'That location is not available for this service.'},{status:400});
    if(code==='ENQUIRY_PHONE_REQUIRED')return NextResponse.json({message:'Add a customer phone number before converting this legacy enquiry.'},{status:400});
    if(code==='ENQUIRY_SERVICE_REQUIRED')return NextResponse.json({message:'Choose a service before converting this enquiry.'},{status:400});
    if(code==='ENQUIRY_ALREADY_CONVERTED')return NextResponse.json({message:'This enquiry is linked to a booking and its status cannot be changed.'},{status:409});
    if(code==='ENQUIRY_NOT_FOUND')return NextResponse.json({message:'The enquiry no longer exists.'},{status:404});
    if(code==='VALIDATION')return NextResponse.json({message:'Please check the submitted values.'},{status:400});
    console.error('[admin] Action failed.',error);
    return NextResponse.json({message:'The change could not be saved.'},{status:500});
  }
}
